### ISSUE TITLE
How to do the rewrites for apache with .htaccess

### ISSUE THREAD

**Issue by noahlearner** [opengeek/statcache#1]
Hi there,
How do you do the rewrite rules for appache servers? Can you add to standard modx distributed htaccess for demonstration purposes?

Many Thanks,

Noah

**Comment by antsplace** [comment]
I'd love to know how you do this too. The example for nginx - would that work when using nginx as a reverse proxy? does it matter where in the nginx config file this line goes?

Would it be possible for the cache file to be generated / updated on the saving of a document rather than on caching?

**Comment by amdbuilder** [comment]
If you don't use .htaccess files to setup FURLs then in theory it should work properly, if you use .htaccess files then you will need to test things further.

If you feel like doing some early alpha testing of statcache on apache, the following code should get you going to some degree.  It's far from production ready, but should get you much closer and with a little refining be production worth.  It has been tested with a contact form, so there is no need to exclude them from statcache.  Any pages with query strings such as pagination should bypass statcache by default, so the 2+ pages will be served by Apache.

This code is tested on my site which lacks page extensions, so you will need to force the content type (https://github.com/opengeek/statcache/issues/3) - this can likely be resolved/eliminated with a little more attention/testing.

This code is not tested with page extensions, however you should be able to remove the first block as it mainly focuses on urls ending with a /

``` htaccess
#Redirect addresses ending in / to the correct page
RewriteCond %{REQUEST_METHOD} !=POST
RewriteCond %{QUERY_STRING} !.*=.*
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{DOCUMENT_ROOT}/statcache/$1/ -d
RewriteRule ^(.*)$ statcache/$1/~index.html [L]

#Redirect other pages
RewriteCond %{REQUEST_METHOD} !=POST
RewriteCond %{QUERY_STRING} !.*=.*
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{DOCUMENT_ROOT}/statcache/$1 -f
RewriteRule ^(.*)$ statcache/$1 [L]
```

DO NOT USE THIS IN A LIVE/PRODUCTION ENVIRONMENT!

**Comment by opengeek** [comment]
FYI I updated the main wiki page with additional nginx and some sample Apache configurations I had previously used when developing this.

@amdbuilder — thanks for your input here; some good ideas we can review and incorporate. Note that this was developed with the intention that whatever Content Type extensions you had would be configured in your web server to respond properly to the extensions written to the cache files (with the exception of site_url and containers ending in /, which would automatically get /~index.html appended to the statcache URI representation).

**Comment by amdbuilder** [comment]
I'll take your htaccess code for a spin and see if it's a little more reliable than my hacked together version.  I did see you don't filter post requests or query strings, was there any reason behind that decision?  They should allow for maximum caching while preserving functionality.

In regards to the content type, it's fine unless you run without the .html in which case you get raw files that aren't served properly.  I guess I could use rewrites to mask the .html, but that seams a little dirty, so a better solution is very welcome.

**Comment by antsplace** [comment]
Thanks guys, I've tested this on an Nginx server and it works a treat!

**Comment by noahlearner** [comment]
Hi Guys thanks for the updates!  I have the plugin working (it is generating cached versions of all pages).  I have amended htaccess file, but it doesn't serve the cached versions of the pages.  I have friendly urls activated. 

I repeat my earlier request for an entire example .htaccess file so that I can see where to put new rewrite rules inside the file.  I'm asking for this because it doesn't seem to be serving the cached versions (and I don't claim to be a rewrite guru- far from it).

Many Thanks,

Noah

**Comment by eerne** [comment]
@noahlearner  

You can test by modifying the .html files in statcache, i.e. i just changed the title's text.

To make it serve the files I needed to modify the .htaccess from

```
# If MODX is in a subdirectory of your DOCUMENT_ROOT,
# add this before your MODX Friendly URLs RewriteCond's and RewriteRule...
RewriteCond %{DOCUMENT_ROOT}/modx/statcache%{REQUEST_URI}~index.html -f
RewriteRule ^/(.*)$ /modx/statcache/$1~index.html [L,QSA]

RewriteCond %{DOCUMENT_ROOT}/modx/statcache%{REQUEST_URI} -f
RewriteRule ^/(.*)$ /modx/statcache/$1 [L,QSA]
```

to

```
# If MODX is directly in your DOCUMENT_ROOT,
# add this before your MODX Friendly URLs RewriteCond's and RewriteRule...
RewriteCond %{DOCUMENT_ROOT}/statcache%{REQUEST_URI}~index.html -f
RewriteRule ^(.*)$ /statcache/$1~index.html [L,QSA]

RewriteCond %{DOCUMENT_ROOT}/statcache%{REQUEST_URI} -f
RewriteRule ^(.*)$ /statcache/$1 [L,QSA] 
```

Note: remove the / after ^

**Comment by antsplace** [comment]
I can't get the apache rewrite rule to work for the index page, whatever I do it doesn't use the file in the folder first, although it will for the other pages.

Statcache is writing the files ok and the static ~index.html page is in the folder

**Comment by opengeek** [comment]
Reopen if this is still an issue...
