### ISSUE TITLE
StatCache OnDocFormSave

### ISSUE THREAD

**Issue by sepiariver** [opengeek/statcache#14]
- [x] setting to use "per resource cache clearing" or whatever lexicon
- [x] when enabled, OnDocFormSave the static cache file for the Resource being edited will be replaced with the new output.
- [x] setting to clear entire cache on cron versus Clear Cache menu item (this is to hopefully protect the cache from Editors who have been trained, for better or worse, to hit the Clear Cache button every time they edit something.)

**Comment by opengeek** [comment]
The property will be `regenerate_on_save` — when this property is enabled in a property set tied to the OnDocFormSave event for the plugin, saving a Resource will trigger the regeneration of any existing static file for the Resource being saved. This regeneration is dependent on the web server being configured to not serve the existing static file when the HTTP User-Agent header has a value of `MODX RegenCache` (or this value can be overridden in the property `regenerate_useragent`)

This is different than the existing `regenerate` option, which is an existing feature that attempts to regenerate _all_ Resources that are statically cacheable when enabled and the plugin is registered with the `OnSiteRefresh` event.

There is no way to enable the clearing of the cache on cron via this component, nor is it really necessary. This can be done with a simple script that calls `rm -rf /path/to/statcache/*` with the appropriate path to the configured statcache directory.

**Comment by opengeek** [comment]
This should be resolved via v1.4.0-pl
