### ISSUE TITLE
Nginx won't restart after adding script to conf

### ISSUE THREAD

**Issue by antsplace** [opengeek/statcache#2]
When I add the suggested lines to the nginx.conf file I can't restart nginx, whatever I do it brings up the error "try_files is not terminated by ";"

As far as my limited knowledge goes with regards to nginx, you can't use {} brackets outside of quoted strings as they are used to signal the start and end of configuration blocks.

You can however just remove these brackets and the code works perfectly:

try_files /statcache$uri/~index.html /statcache$uri $uri $uri/ @modx-rewrite;

**Comment by opengeek** [comment]
Documentation updated...I didn't actually use those, but was under the impression it was allowed. Now I know. :) Thanks for the feedback.
