### ISSUE TITLE
Content Type

### ISSUE THREAD

**Issue by amdbuilder** [opengeek/statcache#3]
In order for resources to be served correct in the case of apache, when the content type for pages has been set to something other than .htaccess, you will need to define their type.  In the case of removing .html you will need to blanket force the type.  Alternatively you could force the .html extension on all files.

.htaccess example:

``` htaccess
<files *>
ForceType text/html
</files>
```

This needs to live in the statcache folder to function.

**Comment by opengeek** [comment]
Added to documentation at https://github.com/opengeek/statcache/wiki
