### ISSUE TITLE
Multi-Context Manager

### ISSUE THREAD

**Issue by vitalized** [opengeek/statcache#5]
I can't seem to get the statcache plugin to work on a multi-websites being servered from a single MODx install (multi-context).  The 'statcache' directory is being created, OnBeforeSaveWebPageCache is ticked & OnSiteRefresh is ticked.
All I get in the 'statcache' directory is a single cached version of a 404 page.

**Comment by amdbuilder** [comment]
The ability to limit statcache to a specific context, a public website vs login area.

**Comment by opengeek** [comment]
@amdbuilder Can you make that a separate issue?

@vitalized Can you provide information on how the multi-context site is configured? e.g. Is it using a plugin, a custom virtual host configurations with their own index.php, or customized index.php with switch statement? Any other custom routing logic? Do the contexts represent sub-domains or separate domains?

**Comment by amdbuilder** [comment]
Done

**Comment by vitalized** [comment]
Hi, the multi-contexts are called from a customized index.php with switch statement. Example here:

/\* setup for multiple domains */
switch(strtolower(MODX_HTTP_HOST)) {

   case 'www.domain.com:80':
   case 'www.domain.com':
      $modx->initialize('domainContext');
      break;

None of the domains are subdomains, they're all top level domains.  There is no other special routing scripts.
I've checked the permissions are correct on the 'statcache' directory

**Comment by gpsietzema** [comment]
Same here. I'd love to be able to use statcache for multiple contexts. We tested both sterc.nl and sterc.eu which are in the same MODX install.

If we visit sterc.eu and continue our browsing session to sterc.nl, it will still serve sterc.eu...
