### ISSUE TITLE
static representation isn't updated when resource is saved

### ISSUE THREAD

**Issue by nurkka** [opengeek/statcache#7]
It seems, that statcache currently doesn't update static representations when a resource is saved. I did some tesing and couldn't get that to work. As a workaround I added some lines of code and now all static files are automatically removed OnDocFormSave.

Is it possible to only renew the static representation OnDocFormSave?

**Comment by opengeek** [comment]
It currently only removes the static files when you select Clear Cache from the Menu. It could be made to clear on additional events.

**Comment by antsplace** [comment]
So how could this be changed to modify when a resource is saved. Could pages be added when resources are saved rather that when they are cached?

My static index page seems to update itself every few hours, is this due to cache timeouts?

**Comment by opengeek** [comment]
> So how could this be changed to modify when a resource is saved. Could pages be added when resources are saved rather that when they are cached?

You could add something to update a specific Resource's static cache page OnDocFormSave, but if the change to that Resource affected anything else in the site, you would need to manually remove all the pages anyway, or have a process attempt to regenerate all the Resources on the site with static representations on each save.

> My static index page seems to update itself every few hours, is this due to cache timeouts?

Only if you have your cache_expires setting (or cache_resource_expires setting) set to a value other than '0'. For instance, a value of '3600' would cause cache items to expire in 1 hour, or 3600 seconds.

**Comment by antsplace** [comment]
I have set cache_expires to 0 but the cache still seems to regenerate itself every so often. Turning sessions off prevents this but isn't ideal.

Not sure how I'd add something to update the resource static cache though...

**Comment by christianseel** [comment]
You can see the basic functionality here: https://github.com/christianseel/statcache/commit/c0e0ecdd2de73dc8c791d1ab01fd7d97c7924bdf

But it's not perfect and more quick & dirty. Needs some improvements.

**Comment by antsplace** [comment]
Works great, personally i like to keep the folder seperate to the modx cache but i can understand that reasoning. Rather than just delete is there a way the file could be regenerated or updated on save.

**Comment by christianseel** [comment]
There should be a way, sure. I remember an extra that did something like that (caching all resources when the site cache is cleared). I will take a look at it and see if I can implement that into statcache for resource updates.

**Comment by christianseel** [comment]
The extra I mentioned is RefreshCache by Bob Ray: https://github.com/BobRay/RefreshCache (This can cache all resource of a site at one time).

In case for statcache we could just request the resource from the frontend, MODX will then do the new caching... This https://github.com/christianseel/statcache/commit/9c3dcb05bec527b640c02fb1bd33e1210f14130c should do the job.

**Comment by antsplace** [comment]
This works a treat, one thing of note is that I turn off sessions for the speed boost and so I added "$modx->getOption('session_enabled', $scriptProperties, 1);" on my install just below the line "$modx->switchContext('web');"  so that sessions are switched on for the file save - does that look right?

**Comment by christianseel** [comment]
I'm not sure why you would write that...
`$modx->getOption('session_enabled', $scriptProperties, 1);` just returns the setting value, nothing more. Also you don't need to "switch on sessions" for caching! There is no need for that.

**Comment by antsplace** [comment]
I was under the impression that it would set the value for the duration of that script process, perhaps I've understood this wrong. I know you don't need sessions enabled for caching however in the past if I've not had sessions on the page hasn't saved using statcache, i've had to switch sessions on for the page to save.

**Comment by opengeek** [comment]
See the changes for issue #14 for a resolution to this issue...
